export {default as Movieinformation}  from "./Movieinformation/Movieinformation"
export {default as Actorinformation}  from "./Actorinformation/Actorinformation"
export {default as Movies}  from "./Movies/Movies"
export {default as Navbar}  from "./Navbar/Navbar"
export {default as Profile}  from "./Profile/Profile"
export {default as Actors}  from "./Actors/Actors"
export {default as Search}  from "./Search/Search"